module.exports.list = [
    '@michellemalkin',
    '@michaeljohns',
    '@johnboehner',
    '@sarahpalinusa',
    '@heritage',
    '@redstate',
    '@glennbeck',
    '@karlrove',
    '@newtgingrich',
    '@fredthompson',
    '@mittromney',
    '@ingrahamangle',
    '@joenbc',
    '@seanhannity',
    '@themrc',
    '@rnc',
    '@dickmorristweet',
    '@loyaltoliberty',
    '@hotairblog',
    '@usconservatives',
// https://www.thoughtco.com/the-top-conservatives-to-follow-on-twitter-3303615

    '@appsame',
    '@chucknellis',
    '@christichat',
    '@carlyfiorina',
    '@drmartyfox',
    '@gop',
    '@erotao',
    '@carminezozzora',
    '@emfingersscout',
    '@a_m_perez',
    '@lrihendry',
    '@marylene58',
    '@reince',
    '@housegop',
    '@meghanmccain',
    '@jstines3',
    '@danieljhannan',
    '@therickwilson',
// https://www.brandwatch.com/blog/react-ranked-influential-republicans-twitter/
];

